In [68]:
import requests
import pandas as pd

# Base URL and parameters for the API request
base_url = "https://open.assembly.go.kr/portal/openapi/nzmimeepazxkubdpn"
api_key = "b20a4845e888423ca019b2d0b94c9c20"
data_type = "json"
age = "21"

# Parameters for pagination
p_index = 1  # Start at page 1
p_size = 1000  # Number of items per page
all_data = []  # List to hold all data

# Continue fetching data until an empty page is received
while True:
    # Update the URL with the current page index and page size
    url = f"{base_url}?KEY={api_key}&Type={data_type}&pIndex={p_index}&pSize={p_size}&AGE='{age}'"

    # Make the API request
    response = requests.get(url)
    response.raise_for_status()  # Will stop the loop if an HTTP error is encountered

    # Load the response data into a JSON format
    data = response.json()

    # Print the keys of the JSON object to understand its structure
    print("Keys available in response:", data.keys())

    # Check if 'nzmimeepazxkubdpn' exists and has the expected structure
    if 'nzmimeepazxkubdpn' in data and len(data['nzmimeepazxkubdpn']) > 1 and 'row' in data['nzmimeepazxkubdpn'][1]:
        rows = data['nzmimeepazxkubdpn'][1]['row']
    else:
        print("Data or 'row' not found in response, ending loop.")
        break  # Break the loop if 'row' is missing or if the structure is different

    # Check if rows are not empty
    if not rows:
        break  # Break the loop if 'row' is empty

    # Now add the retrieved data to the all_data list
    all_data.extend(rows)

    # Increment the page index to get the next page of data in the next iteration
    p_index += 1

# Convert the list of dictionaries to a DataFrame
df = pd.DataFrame(all_data)

# Save the DataFrame to a CSV file
df.to_csv("bill.csv", index=False)

Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['nzmimeepazxkubdpn'])
Keys available in response: dict_keys(['RESULT'])
Data or 'row' not found in response, ending loop.

In [1]:
df = pd.DataFrame(all_data)

NameError: name 'pd' is not defined

In [38]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
df = pd.read_csv("bill.csv", encoding='utf-8')

In [39]:
df.head()

,BILL_ID,BILL_NO,BILL_NAME,COMMITTEE,PROPOSE_DT,PROC_RESULT,AGE,DETAIL_LINK,PROPOSER,MEMBER_LIST,...,LAW_SUBMIT_DT,CMT_PROC_RESULT_CD,CMT_PROC_DT,CMT_PRESENT_DT,COMMITTEE_DT,PROC_DT,COMMITTEE_ID,PUBL_PROPOSER,LAW_PROC_RESULT_CD,RST_PROPOSER
0,PRC_N2W4U0T2S2O1M1N1M1K8T4R2Q0P3P4,2126653,영유아보육법 일부개정법률안,NaN,2024-04-26,NaN,21,http://likms.assembly.go.kr/bill/billDetail.do?billId=PRC_N2W4U0T2S2O1M1N1M1K8T4R2Q0P3P4&ageFrom=21&ageTo=21,강기윤의원 등 10인,http://likms.assembly.go.kr/bill/coactorListPopup.do?billId=PRC_N2W4U0T2S2O1M1N1M1K8T4R2Q0P3P4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"이달곤,김미애,이종성,이용호,정운천,최영희,최재형,윤주경,백종헌",NaN,강기윤
1,PRC_C2K4I0H4G1O6N1O0M3L3O3N3M5K6T2,2126652,이민사회기본법안,NaN,2024-04-25,NaN,21,http://likms.assembly.go.kr/bill/billDetail.do?billId=PRC_C2K4I0H4G1O6N1O0M3L3O3N3M5K6T2&ageFrom=21&ageTo=21,이자스민의원 등 13인,http://likms.assembly.go.kr/bill/coactorListPopup.do?billId=PRC_C2K4I0H4G1O6N1O0M3L3O3N3M5K6T2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"양경규,강은미,심상정,강민정,김민석,배진교,장혜영,도종환,김영주,하태경,한정애,인재근",NaN,이자스민
2,PRC_E2M4L0J4K1J6Y1X0W3U4D2D6E2D2B9,2126651,정부조직법 일부개정법률안,NaN,2024-04-25,NaN,21,http://likms.assembly.go.kr/bill/billDetail.do?billId=PRC_E2M4L0J4K1J6Y1X0W3U4D2D6E2D2B9&ageFrom=21&ageTo=21,이자스민의원 등 13인,http://likms.assembly.go.kr/bill/coactorListPopup.do?billId=PRC_E2M4L0J4K1J6Y1X0W3U4D2D6E2D2B9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"양경규,강은미,심상정,강민정,김민석,배진교,장혜영,인재근,도종환,김영주,하태경,한정애",NaN,이자스민
3,PRC_R2R3Q1R2N2L6L1J7K2J6J1R0P3Q4O9,2126650,국민연금법 일부개정법률안,보건복지위원회,2024-04-25,NaN,21,http://likms.assembly.go.kr/bill/billDetail.do?billId=PRC_R2R3Q1R2N2L6L1J7K2J6J1R0P3Q4O9&ageFrom=21&ageTo=21,강은미의원 등 14인,http://likms.assembly.go.kr/bill/coactorListPopup.do?billId=PRC_R2R3Q1R2N2L6L1J7K2J6J1R0P3Q4O9,...,NaN,NaN,NaN,NaN,2024-04-26,NaN,9700341.0,"심상정,배진교,장혜영,윤미향,이용빈,조오섭,강성희,양향자,양정숙,송갑석,이자스민,양경규,강민정",NaN,강은미
4,PRC_T2S4A0Z3Z0Y8X1T2R5S1Q0P2X4W9V6,2126649,변호사법 일부개정법률안,법제사법위원회,2024-04-25,NaN,21,http://likms.assembly.go.kr/bill/billDetail.do?billId=PRC_T2S4A0Z3Z0Y8X1T2R5S1Q0P2X4W9V6&ageFrom=21&ageTo=21,윤주경의원 등 10인,http://likms.assembly.go.kr/bill/coactorListPopup.do?billId=PRC_T2S4A0Z3Z0Y8X1T2R5S1Q0P2X4W9V6,...,NaN,NaN,NaN,NaN,2024-04-26,NaN,9700006.0,"서병수,조명희,김병욱,조수진,서일준,윤창현,배준영,이헌승,강기윤",NaN,윤주경

In [40]:
df.shape

(23626, 22)

In [41]:
df['proposers'] = df['PUBL_PROPOSER'] + ',' + df['RST_PROPOSER'].str.replace(' ', '')

In [42]:
df['proposers']

0                                                                                                                                                                                                                                                                                                                                                                                         이달곤,김미애,이종성,이용호,정운천,최영희,최재형,윤주경,백종헌,강기윤
1                                                                                                                                                                                                                                                                                                                                                                            양경규,강은미,심상정,강민정,김민석,배진교,장혜영,도종환,김영주,하태경,한정애,인재근,이자스민
2                                                                                                                                                                                                                                                                                                                                                                            양경규,강은미,심상정,강민정,김민석,배진교,장혜영,인재근,도종환,김영주,하태경,한정애,이자스민
3                                                                                                                                                                                                                                                                                                                                                                        심상정,배진교,장혜영,윤미향,이용빈,조오섭,강성희,양향자,양정숙,송갑석,이자스민,양경규,강민정,강은미
4                                                                                                                                                                                                                                                                                                                                                                                         서병수,조명희,김병욱,조수진,서일준,윤창현,배준영,이헌승,강기윤,윤주경
                                                                                                                                                                                                                   ...
23621    강기윤,강대식,강민국,곽상도,구자근,권명호,권영세,김기현,김도읍,김미애,김병욱,김상훈,김석기,김선교,김성원,김승수,김영식,김예지,김용판,김웅,김은혜,김정재,김태흠,김형동,김희곤,김희국,류성걸,박대수,박대출,박덕흠,박성민,박성중,박수영,박완수,박진,박형수,배준영,배현진,백종헌,서범수,서병수,서일준,서정숙,성일종,송석준,송언석,신원식,안병길,양금희,엄태영,유경준,유상범,유의동,윤두현,윤영석,윤재옥,윤주경,윤창현,윤한홍,윤희숙,이달곤,이만희,이명수,이양수,이영,이용,이종성,이주환,이채익,이철규,이헌승,임이자,장제원,전봉민,전주혜,정경희,정동만,정운천,정점식,정진석,정찬민,정희용,조경태,조명희,조수진,조태용,조해진,주호영,지성호,최승재,최춘식,최형두,추경호,태영호,하영제,하태경,한기호,한무경,허은아,홍문표,홍석준,황보승희,이종배
23622    강기윤,강대식,강민국,곽상도,구자근,권명호,권영세,김기현,김도읍,김미애,김병욱,김상훈,김석기,김선교,김성원,김승수,김영식,김예지,김용판,김웅,김은혜,김정재,김태흠,김형동,김희곤,김희국,류성걸,박대수,박대출,박덕흠,박성민,박성중,박수영,박완수,박진,박형수,배준영,배현진,백종헌,서범수,서병수,서일준,서정숙,성일종,송석준,송언석,신원식,안병길,양금희,엄태영,유경준,유상범,유의동,윤두현,윤영석,윤재옥,윤주경,윤창현,윤한홍,윤희숙,이달곤,이만희,이명수,이양수,이영,이용,이종성,이주환,이채익,이철규,이헌승,임이자,장제원,전봉민,전주혜,정경희,정동만,정운천,정점식,정진석,정찬민,정희용,조경태,조명희,조수진,조태용,조해진,주호영,지성호,최승재,최춘식,최형두,추경호,태영호,하영제,하태경,한기호,한무경,허은아,홍문표,홍석준,황보승희,이종배
23623                                                                                                                                                                                                                                                                                                                                                                             권성동,김정재,박덕흠,박성중,송석준,윤영석,윤한홍,이양수,이종배,추경호,홍문표,장제원
23624                                                                                                                                                                                                                                                                                                                                                                             고용진,김경만,김병욱,김병주,김성주,도종환,박병석,박홍근,안민석,유정주,이낙연,신현영
23625                                                                                                                                                                                                                                                                                                                                                             강병원,권칠승,김두관,김영주,김정호,김진표,남인순,도종환,백혜련,송갑석,윤건영,이낙연,전재수,전해철,최인호,박광온
Name: proposers, Length: 23626, dtype: object

In [43]:
df['PROPOSE_DT'] = pd.to_datetime(df['PROPOSE_DT'])
df = df[(df['PROPOSE_DT'] >= '2024-03-28') & (df['PROPOSE_DT'] <= '2024-04-10')]

In [44]:
df = df.loc[:, df.columns.intersection(['BILL_NO','proposers'])]
#df['proposers'] = df['proposers'].str.replace(',', '')
df['counts'] = df.groupby(['BILL_NO']).transform('count')

In [45]:
df.shape

(7, 3)

In [46]:
df_join = df.groupby(['BILL_NO'])['proposers'].apply(list).reset_index()
df_join

   BILL_NO                                                           proposers
0  2126623  [황보승희,박정하,서병수,서범수,임병헌,우신구,이상민,박대수,하태경,이종성,이태규,임이자,최형두,윤영석,이달곤,유의동]
1  2126624                           [유동수,김병욱,맹성규,허종식,김교흥,허숙정,강득구,유기홍,장경태,박찬대]
2  2126625                           [이명수,유상범,김병욱,지성호,최형두,구자근,정동만,김은희,태영호,정진석]
3  2126626                           [이명수,유상범,김병욱,지성호,최형두,구자근,정동만,김은희,태영호,정진석]
4  2126627                           [이명수,유상범,김병욱,지성호,최형두,구자근,정동만,김은희,태영호,정진석]
5  2126628                            [김기현,김석기,구자근,최재형,지성호,김정재,태영호,김예지,이용호,박진]
6  2126629                           [이원택,양이원영,우상호,조정식,고영인,노웅래,박정,강득구,허숙정,김두관]

In [47]:
df_join['proposers'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 7 entries, 0 to 6
Series name: proposers
Non-Null Count  Dtype
--------------  -----
7 non-null      object
dtypes: object(1)
memory usage: 184.0+ bytes

In [48]:
# Print the first few raw string values from the 'proposers' column
for index, value in enumerate(df_join['proposers'].head(10)):
    print(f"Index {index}: {value}")

Index 0: ['황보승희,박정하,서병수,서범수,임병헌,우신구,이상민,박대수,하태경,이종성,이태규,임이자,최형두,윤영석,이달곤,유의동']
Index 1: ['유동수,김병욱,맹성규,허종식,김교흥,허숙정,강득구,유기홍,장경태,박찬대']
Index 2: ['이명수,유상범,김병욱,지성호,최형두,구자근,정동만,김은희,태영호,정진석']
Index 3: ['이명수,유상범,김병욱,지성호,최형두,구자근,정동만,김은희,태영호,정진석']
Index 4: ['이명수,유상범,김병욱,지성호,최형두,구자근,정동만,김은희,태영호,정진석']
Index 5: ['김기현,김석기,구자근,최재형,지성호,김정재,태영호,김예지,이용호,박진']
Index 6: ['이원택,양이원영,우상호,조정식,고영인,노웅래,박정,강득구,허숙정,김두관']

In [49]:
# Transforming each string of names in a list into a list of individual names
def transform_to_individual_names(proposer_list):
    # Check if the list is not empty and contains a string
    if proposer_list and isinstance(proposer_list[0], str):
        # Split the string on commas and strip whitespace from each name
        return [name.strip() for name in proposer_list[0].split(',')]
    return proposer_list

# Apply this transformation to each entry in the 'proposers' column
df_join['proposers'] = df_join['proposers'].apply(transform_to_individual_names)

# Verify the changes
print(df_join['proposers'].head())

0    [황보승희, 박정하, 서병수, 서범수, 임병헌, 우신구, 이상민, 박대수, 하태경, 이종성, 이태규, 임이자, 최형두, 윤영석, 이달곤, 유의동]
1                                   [유동수, 김병욱, 맹성규, 허종식, 김교흥, 허숙정, 강득구, 유기홍, 장경태, 박찬대]
2                                   [이명수, 유상범, 김병욱, 지성호, 최형두, 구자근, 정동만, 김은희, 태영호, 정진석]
3                                   [이명수, 유상범, 김병욱, 지성호, 최형두, 구자근, 정동만, 김은희, 태영호, 정진석]
4                                   [이명수, 유상범, 김병욱, 지성호, 최형두, 구자근, 정동만, 김은희, 태영호, 정진석]
Name: proposers, dtype: object

In [50]:
df_join.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BILL_NO    7 non-null      int64
 1   proposers  7 non-null      object
dtypes: int64(1), object(1)
memory usage: 240.0+ bytes

In [51]:
from itertools import combinations

df_join['proposers'] = df_join['proposers'].apply(lambda l: list(combinations(l, 2)))
df_join = df_join.explode('proposers').dropna()
df_join.head()

   BILL_NO    proposers
0  2126623  (황보승희, 박정하)
0  2126623  (황보승희, 서병수)
0  2126623  (황보승희, 서범수)
0  2126623  (황보승희, 임병헌)
0  2126623  (황보승희, 우신구)

In [52]:
df_join

    BILL_NO    proposers
0   2126623  (황보승희, 박정하)
0   2126623  (황보승희, 서병수)
0   2126623  (황보승희, 서범수)
0   2126623  (황보승희, 임병헌)
0   2126623  (황보승희, 우신구)
..      ...          ...
6   2126629    (박정, 허숙정)
6   2126629    (박정, 김두관)
6   2126629   (강득구, 허숙정)
6   2126629   (강득구, 김두관)
6   2126629   (허숙정, 김두관)

[390 rows x 2 columns]

In [53]:
nt = pd.DataFrame(df_join['proposers'].to_list(), columns=['source','target'])
nt

    source target
0     황보승희    박정하
1     황보승희    서병수
2     황보승희    서범수
3     황보승희    임병헌
4     황보승희    우신구
..     ...    ...
385     박정    허숙정
386     박정    김두관
387    강득구    허숙정
388    강득구    김두관
389    허숙정    김두관

[390 rows x 2 columns]

In [54]:
import networkx as nx

nt['weight'] = nt.groupby(['source', 'target'])['source'].transform('size')
nt = nt.dropna()

G = nx.from_pandas_edgelist(nt, 'source', 'target',
                            create_using=nx.DiGraph(), edge_attr='weight')

nt

    source target  weight
0     황보승희    박정하       1
1     황보승희    서병수       1
2     황보승희    서범수       1
3     황보승희    임병헌       1
4     황보승희    우신구       1
..     ...    ...     ...
385     박정    허숙정       1
386     박정    김두관       1
387    강득구    허숙정       1
388    강득구    김두관       1
389    허숙정    김두관       1

[390 rows x 3 columns]

In [56]:
from pyvis.network import Network

net = Network(notebook=True)
net.from_nx(G)
net.show_buttons(filter_=['nodes', 'edges', 'physics'])
net.show('example.html')

Local cdn resources have problems on chrome/safari when used in jupyter-notebook.